### ISSUE TITLE
Project integration via Pods not working

### ISSUE THREAD

**Issue by jbieler** [fluidsonic/JetPack#16]
Hi!

I would love to use the framework in my project. However I wasn't able to make it work. I did the installation via pod file, now the call to `JetPackKit.initialize()` results in the error `Use of unresolved identifier 'JetPackKit'`. How can I fix this issue?

Are you still actively developing the framework? So far I've copied the code to my project and fixed some bugs that I would love to share with you.

**Comment by fluidsonic** [comment]
Hello Jochen,

happy to hear that it brings you value. Which part caught your interest?

The error message you've mentioned usually only appears if you've forgot `import JetPack` at the top of your Swift file where you're using the library, e.g. for calling `JetPackKit.initialize()`. I also use the library through CocoaPod and it's working just fine. If the import doesn't help you please be more specific about your project setup.

I'll update the README to make it more clear that the import is needed.

Whenever I'm working on an iOS project I use the library and make improvements along the way. I also try to keep it up-to-date with latest Swift releases such as the updates for Swift 4.1 and Swift 4.2 which were released just recently.

If you've found and fixed some bugs then I'd happy to have a look at and integrate your fixes :)

**Comment by jbieler** [comment]
I'm implementing a map application and I needed to find out the border points of my map view for example (e.g. the southwest property etc.). I found two or three bugs, for example in

`func contains(_ point: CLLocationCoordinate2D)` I think the comparison should be `<=` instead of `>=`

I'll try your instructions and let you know. Thanks so far!

**Comment by fluidsonic** [comment]
@jbieler did it work for you?
