### ISSUE TITLE
pod update always resets Swift Language Version to 4.0

### ISSUE THREAD

**Issue by everald** [fluidsonic/JetPack#17]
Running `pod update` or `pod install` always resets the Swift Language Version.

Might be related to this: 
https://github.com/fluidsonic/JetPack/blob/bb9c1c526c73dc9be22e25dac42449c478413ac9/JetPack.podspec#L13

Shouldn't that be `4.2`?

**Comment by fluidsonic** [comment]
Thanks, fixed in a13157e1642090112463f1e628cc119d3d2a49a5
